### ISSUE TITLE
"Pol som har dette ølet" does not load

### ISSUE THREAD

**Issue by kriben** [atlefren/beerdatabase#3]
Steps to reproduce:
1: Select a beer, eg: http://ølmonopolet-zcb.no/pol_beers/3409902
2: Click the "Pol som har dette ølet"-button

Expected:
List of shops.

Actual:
Time-out and incorrectly handled error.

**Comment by atlefren** [comment]
think i've (temporarily?) fixed this, removed some debug printing, but may also be due to re-creation of db. Will watch out for this

**Comment by atlefren** [comment]
Should be fixed now!
